# Generated by Django 5.1.2 on 2024-10-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
